//! On-the-fly topology config generation for Project Voxel.
//!
//! [`VoxelConfig`] (`voxel.toml`) is the single source of truth `voxel` renders
//! every per-node config from, replacing a4x2's static per-node files. This crate
//! is pure Rust (no libfalcon), so it builds and tests on any host.
//!
//! The per-node renderers live in submodules: [`sled`] (sled-agent config),
//! [`frr`] (customer-router `frr.conf`, unnumbered BGP), and [`mgs`]/[`sp`] (the
//! switch-zone MGS-sim + sp-sim configs). The RSS `config-rss.toml` itself is
//! generated by the separate, release-pinned `voxel-rss-gen` binary, which
//! consumes a `VoxelConfig` via its typed omicron config types.

pub mod config;
pub mod frr;
pub mod mgs;
pub mod sled;
pub mod sp;

pub use config::{
    Falcon, Image, Network, RecoverySiloCfg, SledDataLinksSchema, SledDesc, Topology, UplinkCfg,
    VoxelConfig,
};
pub use frr::{FrrNeighbor, FrrRouter};
pub use sled::SledAgentConfig;
