// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Per-sled sled-agent config (`sled-config.toml`) generation.
//!
//! Replaces a4x2's static `config/gN-config.toml` files (which `prep.sh` copied
//! into each sled's cargo-bay). Everything that varies per sled is derived from
//! the sled's index and whether it's a scrimlet:
//!
//! - `sled_mode` - `scrimlet` vs `gimlet`
//! - `sidecar_revision.soft_propolis.front_port_count` - 2 (scrimlet) vs 1
//! - `vdevs` - `m2_g{i}_*` / `u2_g{i}_*`
//! - `switch_zone_maghemite_links` - the sidecar rear tfports (scrimlet) vs none
//! - `data_link` / `data_links` - placeholders; `gimlet-launch.sh` rewrites them
//!   from the live jumbo-NIC enumeration at boot (topology-dependent)
//! - `[sprockets]` cert paths - per-sled identity index
//!
//! The non-varying parts mirror the known-good a4x2 config the current image
//! consumes. Like `rss.rs`/`frr.rs` this is rendered by hand; it can move to the
//! typed, release-pinned omicron config types alongside the RSS renderer later.

use std::fmt::Write as _;

/// Inputs for one sled's `sled-config.toml`.
#[derive(Debug, Clone)]
pub struct SledAgentConfig {
    /// Sled index (`g{index}`), drives vdev + sprockets identity.
    pub index: usize,
    /// Scrimlet (runs a switch zone) vs plain gimlet.
    pub scrimlet: bool,
    /// Directory the sprockets test keys live in.
    pub sprockets_dir: String,
    /// Total sleds in the rack. Each scrimlet's SoftNPU gets one sled-facing
    /// (rear) port per sled (voxel topo wires `softnpu_link` scrimlet->every
    /// sled), so the rear-port count + the `tfportrear` list must scale with
    /// it. Otherwise, sleds past the 4th land in the front/uplink port range
    /// and fall off the underlay (the >4-sled bug).
    pub num_sleds: usize,
    /// Fabric (transit) routers - the scrimlet's uplink (front) port count
    /// (`softnpu_link` scrimlet->every fabric router).
    pub num_fabric_routers: usize,
    /// Switch-to-switch interconnects this scrimlet is on - extra FRONT ports
    /// (`softnpu_links` sidecar<->sidecar), wired after the fabric uplinks, so
    /// the front-port budget must include them or the link lands off the ASIC.
    pub num_interconnects: usize,
    /// Sled-agent `data_links` config shape (see [`crate::config::SledDataLinksSchema`]).
    pub data_links: crate::config::SledDataLinksSchema,
    /// Sled-agent disks config shape (see [`crate::config::SledDisksSchema`]).
    pub disks: crate::config::SledDisksSchema,
}

impl SledAgentConfig {
    pub fn new(
        index: usize,
        scrimlet: bool,
        data_links: crate::config::SledDataLinksSchema,
        disks: crate::config::SledDisksSchema,
    ) -> Self {
        Self {
            index,
            scrimlet,
            sprockets_dir: "/opt/cargo-bay/sprockets".into(),
            // Counts mirror the original fixed 4-sled / 2-fabric-router layout
            // (used by the build-time baked config + tests); per-launch staging
            // calls `with_topology` for the live counts.
            num_sleds: 4,
            num_fabric_routers: 2,
            num_interconnects: 0,
            data_links,
            disks,
        }
    }

    /// Size the scrimlet SoftNPU's ports for the live rack: a rear port per sled
    /// + a front port per fabric router. Required for >4-sled racks.
    pub fn with_topology(
        mut self,
        num_sleds: usize,
        num_fabric_routers: usize,
    ) -> Self {
        self.num_sleds = num_sleds;
        self.num_fabric_routers = num_fabric_routers;
        self
    }

    /// Add `n` switch-to-switch interconnect front ports (beyond the fabric
    /// uplinks) to this scrimlet's SoftNPU budget.
    pub fn with_interconnects(mut self, n: usize) -> Self {
        self.num_interconnects = n;
        self
    }

    /// Select the sled-agent `data_links` config shape (see
    /// [`crate::config::SledDataLinksSchema`]).
    pub fn with_data_links_schema(
        mut self,
        schema: crate::config::SledDataLinksSchema,
    ) -> Self {
        self.data_links = schema;
        self
    }

    /// Render the `sled-config.toml` text.
    pub fn render(&self) -> String {
        let i = self.index;
        let mut o = String::new();

        writeln!(o, "# Sled Agent configuration - generated by voxel (g{i}).")
            .unwrap();
        writeln!(o).unwrap();

        let sled_mode = if self.scrimlet { "scrimlet" } else { "gimlet" };
        writeln!(o, "sled_mode = \"{sled_mode}\"").unwrap();

        // Scrimlet SoftNPU ports: a sled-facing (rear) port per sled + an uplink
        // (front) port per fabric router. dpd assigns the rear ports first, so
        // they line up with the topology's softnpu_link order (sleds, then fabric
        // routers). Gimlets have no switch zone, so the values are vestigial.
        let front = if self.scrimlet {
            self.num_fabric_routers + self.num_interconnects
        } else {
            1
        };
        let rear = self.num_sleds;
        writeln!(
            o,
            "sidecar_revision.soft_propolis = {{ front_port_count = {front}, rear_port_count = {rear} }}"
        )
        .unwrap();

        writeln!(o, "skip_timesync = false").unwrap();
        writeln!(o).unwrap();

        // Emulated M.2 (×2) + U.2 (×5) vdevs, named per sled. The field shape
        // changed across omicron eras (flat `vdevs` list -> tagged `external_disks`
        // enum), so render per the selected schema (see SledDisksSchema).
        let mut vdevs: Vec<String> =
            vec![format!("m2_g{i}_0.vdev"), format!("m2_g{i}_1.vdev")];
        for u in 0..5 {
            vdevs.push(format!("u2_g{i}_{u}.vdev"));
        }
        match self.disks {
            crate::config::SledDisksSchema::Vdevs => {
                writeln!(o, "vdevs = [").unwrap();
                writeln!(o, "  \"{}\",", vdevs[0]).unwrap();
                writeln!(o, "  \"{}\",", vdevs[1]).unwrap();
                writeln!(o).unwrap();
                for v in &vdevs[2..] {
                    writeln!(o, "  \"{v}\",").unwrap();
                }
                writeln!(o, "]").unwrap();
            }
            crate::config::SledDisksSchema::ExternalDisks => {
                // Inline table (TOML inline tables can't span lines), mirroring
                // omicron's `ExternalDisks::Virtual { vdevs }` (#[serde(tag="kind")]).
                let list = vdevs
                    .iter()
                    .map(|v| format!("\"{v}\""))
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    o,
                    "external_disks = {{ kind = \"virtual\", vdevs = [{list}] }}"
                )
                .unwrap();
            }
            crate::config::SledDisksSchema::Hardcoded => {
                // `Virtual { vdevs }` and `HardcodedPhysical { disks }` merged
                // into one `Hardcoded { vdevs, disks }`. Both fields are
                // required; voxel injects no raw disks, so `disks` is empty.
                let list = vdevs
                    .iter()
                    .map(|v| format!("\"{v}\""))
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(
                    o,
                    "external_disks = {{ kind = \"hardcoded\", vdevs = [{list}], disks = [] }}"
                )
                .unwrap();
            }
        }
        writeln!(o).unwrap();

        writeln!(o, "vmm_reservoir_percentage = 0").unwrap();
        writeln!(o).unwrap();

        // Placeholder - gimlet-launch.sh patches data_link/data_links from the
        // live jumbo-NIC enumeration (the underlay ordering is topology-
        // dependent, so a static value can't be right for every layout).
        let data_link = if self.scrimlet { "vioif1" } else { "vioif0" };
        writeln!(o, "data_link = \"{data_link}\"").unwrap();
        writeln!(o).unwrap();

        // Scrimlets feed the sidecar rear tfports into oxz_switch for transit
        // Maghemite; gimlets need none.
        if self.scrimlet {
            writeln!(o, "switch_zone_maghemite_links = [").unwrap();
            for n in 0..self.num_sleds {
                writeln!(o, "    \"tfportrear{n}_0\",").unwrap();
            }
            writeln!(o, "]").unwrap();
        } else {
            writeln!(o, "switch_zone_maghemite_links = [ ]").unwrap();
        }
        writeln!(o).unwrap();

        let devices = if self.scrimlet {
            "\"vioif1\", \"vioif2\""
        } else {
            "\"vioif0\", \"vioif1\""
        };
        let data_links = match self.data_links {
            crate::config::SledDataLinksSchema::List => format!("[{devices}]"),
            crate::config::SledDataLinksSchema::Tagged => {
                format!("{{ kind = \"virtual\", devices = [{devices}] }}")
            }
        };
        writeln!(o, "data_links = {data_links}").unwrap();
        writeln!(o).unwrap();

        writeln!(o, "[dropshot]").unwrap();
        writeln!(o, "default_request_body_max_bytes = 1048576").unwrap();
        writeln!(o).unwrap();

        writeln!(o, "[log]").unwrap();
        writeln!(o, "level = \"info\"").unwrap();
        writeln!(o, "mode = \"file\"").unwrap();
        writeln!(o, "path = \"/dev/stdout\"").unwrap();
        writeln!(o, "if_exists = \"append\"").unwrap();
        writeln!(o).unwrap();

        // Pre-generated test sprockets keys/roots, per-sled identity index.
        let d = &self.sprockets_dir;
        writeln!(o, "[sprockets]").unwrap();
        writeln!(
            o,
            "resolve = {{ which = \"local\", priv_key = \"{d}/test-sprockets-auth-{i}.key.pem\", cert_chain = \"{d}/test-sprockets-auth-{i}.certlist.pem\" }}"
        )
        .unwrap();
        writeln!(
            o,
            "attest = {{ which = \"local\", priv_key = \"{d}/test-alias-{i}.key.pem\", cert_chain = \"{d}/test-alias-{i}.certlist.pem\", log = \"{d}/test-sprockets-log.bin\", test_corpus = [ \"{d}/test-measurements.corim\" ] }}"
        )
        .unwrap();
        writeln!(o, "roots = [\"{d}/test-root-a.cert.pem\"]").unwrap();

        o
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{SledDataLinksSchema, SledDisksSchema};

    /// The rendered config is valid TOML with the expected per-sled fields.
    fn parse(s: &str) -> toml::Value {
        toml::from_str(s).expect("renders valid TOML")
    }

    /// Oldest-era construction, the shape most render tests assert.
    fn old(index: usize, scrimlet: bool) -> SledAgentConfig {
        SledAgentConfig::new(
            index,
            scrimlet,
            SledDataLinksSchema::List,
            SledDisksSchema::Vdevs,
        )
    }

    #[test]
    fn scrimlet_fields() {
        let v = parse(&old(0, true).render());
        assert_eq!(v["sled_mode"].as_str(), Some("scrimlet"));
        assert_eq!(
            v["sidecar_revision"]["soft_propolis"]["front_port_count"]
                .as_integer(),
            Some(2)
        );
        let links = v["switch_zone_maghemite_links"].as_array().unwrap();
        assert_eq!(links.len(), 4);
        assert_eq!(links[0].as_str(), Some("tfportrear0_0"));
        let vdevs = v["vdevs"].as_array().unwrap();
        assert_eq!(vdevs.len(), 7);
        assert_eq!(vdevs[0].as_str(), Some("m2_g0_0.vdev"));
        assert!(
            v["sprockets"]["resolve"]["priv_key"]
                .as_str()
                .unwrap()
                .contains("test-sprockets-auth-0")
        );
    }

    #[test]
    fn scrimlet_softnpu_ports_scale_with_sled_count() {
        // A 6-sled rack: the scrimlet SoftNPU needs a rear port per sled (so all
        // 6 sleds land in the underlay range, not the front/uplink range) and a
        // front port per fabric router. Regression for the >4-sled fabric bug.
        let v = parse(&old(0, true).with_topology(6, 2).render());
        let sp = &v["sidecar_revision"]["soft_propolis"];
        assert_eq!(sp["rear_port_count"].as_integer(), Some(6));
        assert_eq!(sp["front_port_count"].as_integer(), Some(2));
        let links = v["switch_zone_maghemite_links"].as_array().unwrap();
        assert_eq!(links.len(), 6);
        assert_eq!(links[5].as_str(), Some("tfportrear5_0"));
    }

    #[test]
    fn interconnects_bump_scrimlet_front_ports() {
        // A scrimlet on 1 interconnect: front = num_fabric_routers + 1 (the
        // extra QSFP for the sidecar<->sidecar link). Rear unchanged.
        let v = parse(
            &old(0, true).with_topology(4, 2).with_interconnects(1).render(),
        );
        let sp = &v["sidecar_revision"]["soft_propolis"];
        assert_eq!(sp["front_port_count"].as_integer(), Some(3));
        assert_eq!(sp["rear_port_count"].as_integer(), Some(4));
        // Gimlets have no switch zone, so interconnects don't apply.
        let g = parse(
            &old(1, false).with_topology(4, 2).with_interconnects(1).render(),
        );
        assert_eq!(
            g["sidecar_revision"]["soft_propolis"]["front_port_count"]
                .as_integer(),
            Some(1)
        );
    }

    #[test]
    fn gimlet_fields() {
        let v = parse(&old(1, false).render());
        assert_eq!(v["sled_mode"].as_str(), Some("gimlet"));
        assert_eq!(
            v["sidecar_revision"]["soft_propolis"]["front_port_count"]
                .as_integer(),
            Some(1)
        );
        assert!(
            v["switch_zone_maghemite_links"].as_array().unwrap().is_empty()
        );
        let vdevs = v["vdevs"].as_array().unwrap();
        assert_eq!(vdevs[2].as_str(), Some("u2_g1_0.vdev"));
        assert!(
            v["sprockets"]["attest"]["priv_key"]
                .as_str()
                .unwrap()
                .contains("test-alias-1")
        );
    }

    #[test]
    fn data_links_schema_shapes() {
        // Default (List) renders the legacy array shape.
        let list = parse(&old(0, false).render());
        assert!(list["data_links"].as_array().is_some(), "List => array");
        // Tagged renders omicron main's DataLinks enum: { kind, devices }.
        let tagged = parse(
            &SledAgentConfig::new(
                0,
                false,
                SledDataLinksSchema::Tagged,
                SledDisksSchema::Vdevs,
            )
            .render(),
        );
        assert_eq!(tagged["data_links"]["kind"].as_str(), Some("virtual"));
        assert_eq!(
            tagged["data_links"]["devices"].as_array().unwrap().len(),
            2
        );
    }

    #[test]
    fn disks_schema_shapes() {
        // Default (Vdevs) renders the legacy flat `vdevs` array.
        let flat = parse(&old(0, false).render());
        assert_eq!(flat["vdevs"].as_array().unwrap().len(), 7);
        assert!(flat.get("external_disks").is_none());
        // ExternalDisks renders omicron main's tagged enum: { kind, vdevs }.
        let ext = parse(
            &SledAgentConfig::new(
                0,
                false,
                SledDataLinksSchema::List,
                SledDisksSchema::ExternalDisks,
            )
            .render(),
        );
        assert!(ext.get("vdevs").is_none(), "flat vdevs must be gone");
        assert_eq!(ext["external_disks"]["kind"].as_str(), Some("virtual"));
        assert_eq!(ext["external_disks"]["vdevs"].as_array().unwrap().len(), 7);
    }

    /// omicron merged `Virtual { vdevs }` and `HardcodedPhysical { disks }` into
    /// `Hardcoded { vdevs, disks }`. Emitting the old `virtual` variant puts
    /// sled-agent into MAINTENANCE with "unknown variant `virtual`, expected
    /// `hardcoded` or `detect_physical`", so both the tag and the now-required
    /// empty `disks` list matter.
    #[test]
    fn hardcoded_disks_schema_matches_omicron_main() {
        let cfg = parse(
            &SledAgentConfig::new(
                0,
                false,
                SledDataLinksSchema::List,
                SledDisksSchema::Hardcoded,
            )
            .render(),
        );
        assert!(cfg.get("vdevs").is_none(), "flat vdevs must be gone");
        let disks = &cfg["external_disks"];
        assert_eq!(disks["kind"].as_str(), Some("hardcoded"));
        assert_eq!(disks["vdevs"].as_array().unwrap().len(), 7);
        assert_eq!(
            disks["vdevs"][0].as_str(),
            Some("m2_g0_0.vdev"),
            "vdev naming must survive the shape change"
        );
        assert!(
            disks["disks"].as_array().expect("disks is required").is_empty(),
            "voxel injects no raw disks"
        );
    }
}
